# Generated by Django 5.1.6 on 2025-03-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
