# Generated by Django 5.1.7 on 2025-03-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_route_route_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='name',
            new_name='stop_name',
        ),
    ]
