# Generated by Django 5.1.7 on 2025-04-01 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicTransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('origin_coordinates', models.JSONField(default=dict)),
                ('destination_coordinates', models.JSONField(default=dict)),
                ('polyline', models.TextField()),
                ('route_short_name', models.CharField(max_length=30)),
                ('route_long_name', models.CharField(max_length=70)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_transport_routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
