# Generated by Django 5.1.7 on 2025-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_publictransportroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='publictransportroute',
            name='transport',
            field=models.CharField(choices=[('None', 'None'), ('Bus', 'Bus'), ('Tram', 'Tram')], default='None', max_length=255),
        ),
    ]
