# Generated by Django 5.1.7 on 2025-04-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_publictransportroute_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='publictransportroute',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='publictransportroute',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publictransportroute',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
