# Generated by Django 5.1.7 on 2025-04-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_publictransportroute_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publictransportroute',
            name='agency_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
