# Generated by Django 5.2.1 on 2025-05-17 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_prize1_user_prize2_user_prize3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polution_Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('point1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point1', to='api.polution_point')),
                ('point2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point2', to='api.polution_point')),
                ('point3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point3', to='api.polution_point')),
                ('point4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point4', to='api.polution_point')),
                ('point5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point5', to='api.polution_point')),
            ],
        ),
    ]
