# Generated by Django 5.2.1 on 2025-05-17 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_polution_point_daily_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_tasks',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
