# Generated by Django 5.2.1 on 2025-05-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_daily_tasks_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='polution_point',
            name='decibels',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
