# Generated by Django 5.2.1 on 2025-05-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_co2_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co2_points',
            name='address',
        ),
    ]
