# Generated by Django 5.1.6 on 2025-03-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_article_disliked_by_article_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
